function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data

%  Auto-generated by MATLAB on 06-Feb-2025 15:27:41

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','cos(x)','Color',[1 0 1]);

% Create text
text('Parent',axes1,'String','Hola','Position',[50 0.5 0]);

% Create text
text('Parent',axes1,'VerticalAlignment','baseline','String','NEGRO',...
    'Position',[61.2359550561798 0.0729729729729729 0]);

% Create ylabel
ylabel('Amplitud(m)');

% Create xlabel
xlabel('Tiempo (s)');

% Create title
title('Gráfica Cos(x)');

box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'XColor',[0.24705882370472 0.24705882370472 0.24705882370472],...
    'YColor',[0.24705882370472 0.24705882370472 0.24705882370472],'ZColor',...
    [0.24705882370472 0.24705882370472 0.24705882370472]);
% Create colorbar
colorbar(axes1);

